# Generated by Django 4.1.7 on 2023-06-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_points_alter_candidate_testattempted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='testAttempted',
            new_name='test_attempted',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result_id',
            new_name='resultid',
        ),
    ]
